#!/bin/bash

pacman -Sy --needed pacman-contrib --noconfirm
if [[ ! -f /etc/pacman.d/mirrorlist.backup ]]; then
  cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
fi
curl -so "/etc/pacman.d/mirrorlist.tmp" "https://www.archlinux.org/mirrorlist/?country=BR&use_mirror_status=on"
sed -i 's/^#Server/Server/g' "/etc/pacman.d/mirrorlist.tmp"
rankmirrors /etc/pacman.d/mirrorlist.tmp >/etc/pacman.d/mirrorlist
rm /etc/pacman.d/mirrorlist.tmp
chmod +r /etc/pacman.d/mirrorlist
cat /etc/pacman.d/mirrorlist